connect:
  request_headers:
    User-Agent: ......
    Accept: ......
  transmission:
    host: localhost
    port: 9091
    user: xxxx
    password: xxxx

schedule:
  path: ./Downloads/Transmission
  interval: 3600
  active:
  - Sample

tasks:
  Sample:
    path: ......
    rss: ......
    params:
      keyword: ......
      team_id: ......
    filter:
      after_time: 2019.1.1
      include: ......
      exclude: ......
